[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
xml-rs = "0.8.22"
foldhash = "0.1.3"
hashbrown = { version = "0.15.0", features = ["rayon"] }

[features]
dbg = []

[[bin]]
name = "search"
path = "main.rs"
